### PR TITLE
Fix alertSheet crash ( which removed from iOS10 )

### PR DESCRIPTION
**Pull request by iMokhles**

### CODE REVIEW

**Comment by ashikase** [comment]
Thank you, I was aware of the issue and already had a fix in preparation, but I am currently considering removing this component altogether.

**Comment by iMokhles** [comment]
which component ? the filter and no email alerts ?
if yes i do like the filter alert ( because it happened to me a lot to remove the plist accidentally and CrashReporter alerted me that the tweak don't have filter.

**Comment by ashikase** [comment]
The "scanner" component. I still need to investigate, but I believe that recent versions of CydiaSubstrate include similar functionality, making scanner obsolete.

**Comment by rparanson** [comment]
Any chance for a 10.3.3 update to Crashreporter. Crashes on open.

**Review by ggg44 — APPROVED** [review]

**Comment by rparanson** [comment]
Thank you but 10.3.3 still seems to be crashing on load for me (iphone 5c32
bit)



Rick Aranson
raranson@gmail.com
678-404-1818

   - www.linkedin.com/in/raranson/

**Comment by MODZ4FUN420** [comment]
Crashreporter isn’t working on iOS 12 at all

**Pull request closed without merging**
